version: '3'
services:

  # sonar-codequality-collector:
  #  environment:
  #  - SONAR_URL=http://192.168.99.101:9000
  #  - SONAR_CRON=0 * * * * *
  #  - SONAR_USERNAME=admin
  #  - SONAR_PASSWORD=admin
  #  - SONAR_VERSION=6.7
  #  - SONAR_METRICS=ncloc,violations,new_vulnerabilities,critical_violations,major_violations,blocker_violations,tests,test_success_density,test_errors,test_failures,coverage,line_coverage,sqale_index,alert_status,quality_gate_details

  db:
    environment: 
     - HYGIEIA_DB=dashboarddb
     - HYGIEIA_DB_USER=dashboarduser
     - HYGIEIA_DB_PWD=dbpassword
  api:
    environment: 
    - KEY=gwv3PTFoJbyYGjKzpz3gAQgcXr8cdZQ+

  jenkins-build:
    environment: 
    - JENKINS_URL[0]=http://192.168.99.102:8080
    - NICE_NAME[0]=Jenkins
    - PIPELINE_ENV[0]=[DEV,QA,PROD]
    - USERNAME[0]=admin
    - APIKEY[0]=11a2ddc8e251c5870dd7ea4b92e2de665f
  
